services: 
  django:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: monprojet_django
    container_name: monprojet_django_conteneur
    env_file: 
      - "./envs"
    ports:
      - "8001:8000"
    volumes:
      - .:/app
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: monprojet_db_conteneur
    env_file: 
      - "./envs"
    ports:
      - "15532:5432"
    volumes:
      - monprojet_postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6
    container_name: monprojet_redis_conteneur

volumes:
  monprojet_postgres_data: